version: "3.8"

services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php7.4
      - php8.1.2
    volumes:
      - ../:/var/www/vhosts
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./snippets:/etc/nginx/snippets
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./vhosts:/etc/nginx/vhosts
  php7.4:
    image: php:7.4-fpm
    container_name: php7.4
    expose:
      - "9000"
    volumes:
      - ../:/var/www/vhosts
    working_dir: /var/www/vhosts
  php8.1.2:
    image: php:8.1.2-fpm
    container_name: php8.1.2
    expose:
      - "9000"
    volumes:
      - ../:/var/www/vhosts
    working_dir: /var/www/vhosts
